### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by fsmanuel** [funkensturm/statuspage#6]

**Comment by halo** [comment]
Where does the redirect come from? I don't see a custom domain configured in the gh-pages branch. http://funkensturm.github.io/statuspage -> http://www.funkensturm.com/statuspage/

I was thinking about adding more to the README and linking to the "demo" page. Then again, I think it would be nice with a "demo" flag in the configuration and then there would be some sort of popup explaining what it is and how it works? So we would have everything in one place.

**Comment by fsmanuel** [comment]
I would prefer a "fork me on github" label and every else in the readme.

I think it's important that we have a short how to contribute section with the concept of the provider config explained.

We could also script a interactive tour...

**Comment by fsmanuel** [comment]
The redirect comes from the github org

**Comment by halo** [comment]
Said and done. There is a github page now at http://www.funkensturm.com/statuspage/

**Comment by fsmanuel** [comment]
Nice! Good job!

**Comment by fsmanuel** [comment]
Did you use `ember build --env production` for the build?

**Comment by halo** [comment]
Yes. https://github.com/funkensturm/statuspage#deploying

**Comment by fsmanuel** [comment]
👍
