### ISSUE TITLE
Make AWS RSS id inheritable

### ISSUE THREAD

**Issue by halo** [funkensturm/statuspage#8]
[This thing](https://github.com/funkensturm/statuspage/blob/389456957c3ec0c8ec593fe8916cda2c0d89c7f3/app/providers/aws-s3-eu-central-1.js#L6-L14) should be in [the parent](https://github.com/funkensturm/statuspage/blob/389456957c3ec0c8ec593fe8916cda2c0d89c7f3/app/lib/providers/aws-rss.js#L10-L13). Because it is so complicated and always looks the same for every service.

But the ID of the service, i.e. `s3-eu-central-1` specified [here](https://github.com/funkensturm/statuspage/blob/389456957c3ec0c8ec593fe8916cda2c0d89c7f3/app/providers/aws-s3-eu-central-1.js#L9) needs to be customized when inheriting.

Any idea on how to achieve that? I had no luck interpolating that part of the URL.

**Comment by fsmanuel** [comment]
You can add a endpointUrl property and make `ajaxOptions` a computed property that depends on endpointUrl.

```js
// aws-rss.js
export default Provider.extend({
  ajaxOptions: computed('endpointUrl', function() {
    return {
      'url': 'https://query.yahooapis.com/v1/public/yql',
      'data': {
        'q': `SELECT * FROM rss WHERE url="${get(this, 'endpointUrl')}"`,
        'format': 'json',
        'jsonCompat': 'new'
      },
      'dataType': 'jsonp'
    }
  })
})

// aws-cloudfront.js
import Provider from 'statuspage/lib/providers/aws-rss'

export default Provider.extend({
  name: 'Amazon CloudFront',
  endpointUrl: 'http://status.aws.amazon.com/rss/cloudfront.rss'
})

// aws-s3-eu-central-1.js
import Provider from 'statuspage/lib/providers/aws-rss'

export default Provider.extend({
  name: 'Amazon Simple Storage Service (Frankfurt)',
  endpointUrl: 'http://status.aws.amazon.com/rss/s3-eu-central-1.rss'
})
```
