### ISSUE TITLE
Green tests in phantom 2.

### ISSUE THREAD

**Issue by halo** [funkensturm/statuspage#9]
They pass in the browser, but phantom 2 cannot handle syncronous ajax requests (we use synchronous requests to load json fixtures in our tests).

I guess we have to wait for phantom 2.2 which [supposedly solves](https://github.com/ariya/phantomjs/issues/13908) this [issue](https://github.com/ariya/phantomjs/issues/13891)

**Comment by fsmanuel** [comment]
Or you change to chrome see [travis.yml](https://github.com/DockYard/ember-one-way-controls/blob/master/.travis.yml) for the configuration.

**Comment by halo** [comment]
Turns out, it had [nothing to do](https://github.com/funkensturm/statuspage/commit/1c96e56f1267d551102b4b317f5d7c32a2ea5a5f) with Phantom. Chrome failed locally as well.
